### ISSUE TITLE
Please mark 6.2.0 as broken

### ISSUE THREAD

**Issue by ccordoba12** [conda-forge/jupyter_client-feedstock#56]
Given that you yanked that release in PyPI, I think it's necessary to mark that release as broken here, right?

Please let me know if you need a hand with it.

**Comment by davidbrochart** [comment]
The [PR was merged](https://github.com/conda-forge/admin-requests/pull/256) and it is marked as broken already.

**Comment by ccordoba12** [comment]
Ok, but sorry for the noise. We're seeing a strange error in Spyder when restarting kernels and I thought it was related to that.
