### ISSUE TITLE
Mark 7.3.2 build 0 as broken?

### ISSUE THREAD

**Issue by maresb** [conda-forge/jupyter_client-feedstock#80]
### Comment:

The build prior to the fix from https://github.com/conda-forge/jupyter_client-feedstock/pull/77 (fix pyzmq version) just caused me an issue in https://github.com/conda-forge/rise-feedstock/issues/38. Could we mark it as broken to prevent further issues?

**Comment by maresb** [comment]
Created a draft PR in admin-requests to mark this as broken: https://github.com/conda-forge/admin-requests/pull/455

**Comment by davidbrochart** [comment]
Fixed in https://github.com/conda-forge/admin-requests/pull/455.

**Comment by davidbrochart** [comment]
Thank you!
